### ISSUE TITLE
Silent break on Firefox when order is NaN

### ISSUE THREAD

**Issue by Radivarig** [Khan/simple-markdown#10]
From #8
```js
order: SimpleMarkdown.defaultRules.link -0.5
```
is actually `NaN` as it should be
```js
order: SimpleMarkdown.defaultRules.link.order -0.5
```
Interestingly, it works on Chrome and breaks silently on Firefox! :)

**Comment by ariabuckles** [comment]
thanks! i put a commit in, but i'm actually thinking it might be better to warn. Sorting partially based on number and partially based on name seems like a recipe for disaster.

**Comment by ariabuckles** [comment]
Version 0.0.7 now warns in this case :).
