### ISSUE TITLE
Case where italics do not parse

### ISSUE THREAD

**Issue by night** [Khan/simple-markdown#16]
One of our users reported a case where italics were not parsing. Anytime you have an italic phrase ending with a single letter, it does not parse.

Example:

    > JSON.stringify(SimpleMarkdown.defaultBlockParse('*test i*'))
    '[{"content":[{"content":"*test i","type":"text"},{"content":"*","type":"text"}],"type":"paragraph"}]'

**Comment by ariabuckles** [comment]
Ooph, that's not good. I'll look into it and try to get back to you by tomorrow; should be fixable.

Thanks for letting me know!

**Comment by ariabuckles** [comment]
Going to give @xymostech and @alopatin time to look at #17 if they want to, since messing with italics parsing could affect khan academy questions, then hopefully merge + publish later today :).

**Comment by ariabuckles** [comment]
Okay I put in a fix for this case in NPM version 0.1.3 .

I tried to fix some more complicated nesting cases in 0.2.0, but I think that introduces bugs in different nesting cases, so I'm going to look into fixing those and would recommend sticking with 0.1.3 for now (and will post here if I manage to fix those).

**Comment by night** [comment]
I was not expecting such a fast fix for something so minor, thanks! 👍

**Comment by ariabuckles** [comment]
yw <3!
