### ISSUE TITLE
Another parser issue, this time with links

### ISSUE THREAD

**Issue by night** [Khan/simple-markdown#20]
Discord recently added Webhooks, which allow services to post custom links into chat (we don't allow this otherwise to protect users from bad links). I noticed during testing that links containing escaped markdown, like `\)` do not properly escape.

For example, `[test link](https://test.link/\(test\))` becomes `test link)` with simple-markdown. GitHub renders this properly: [test link](https://test.link/\(test\))

Here's a console output too:

    > JSON.stringify(SimpleMarkdown.defaultBlockParse('[test link](https://test.link/\(test\))'))
    '[{"content":[{"content":[{"content":"test link","type":"text"}],"target":"https://test.link/(test","type":"link"},{"content":")","type":"text"}],"type":"paragraph"}]'

**Comment by ariabuckles** [comment]
Interesting; I'm a bit surprised GFM lets you \\-escape characters in urls. That said, \\'s shouldn't be valid in links anyways, so this seems fine to change.

We could also change the link matching function to handle nested parentheses correctly (replacing the regex matcher with a function that loops through characters), which is more verbose but probably worthwhile long-term.

In general the escape rules work well at the start of rules (cause `text` handles them well), but there are some rules that don't handle them correctly that I should fix (looking at bold/italics recently).

Anyways, should be able to get to fixing this by tomorrow.

**Comment by ariabuckles** [comment]
Fixed in af77481 / 0.2.1 :)
