### ISSUE TITLE
Allow one level of balanced parens in link urls, per CommonMark

### ISSUE THREAD

**Issue by ariabuckles** [Khan/simple-markdown#21]
See [the section on this in the CommonMark spec](http://spec.commonmark.org/0.26/#example-465)

simple-markdown does not try to conform to CommonMark, but does try to be compatible when possible and choose sensible defaults, which CommonMark also tries to do.

**Comment by faergeek** [comment]
Is this already being worked on somewhere or I could help with this and submit a PR?

**Comment by ariabuckles** [comment]
It's not being worked on anywhere; you're welcome to help and submit a PR!

I'd recommend checking out the regular expression string `LINK_HREF_AND_TITLE` (which is pretty messy, sorry!). That could probably be broken up across a few lines with comments explaining what's going on, and then you could add a clause for balanced parentheses groups.

**Comment by faergeek** [comment]
Am I right that there's no some commented out tests for such behaviour or something like that? Should I write my own?

**Comment by ariabuckles** [comment]
Correct, there aren't tests for this yet. You're welcome to write them! Or welcome to contribute without adding formal tests.
