### ISSUE TITLE
Handle nested ***bold** and italics* correctly

### ISSUE THREAD

**Issue by ariabuckles** [Khan/simple-markdown#22]
See #19 for a potential solution to this.

**Comment by kevinbarabash** [comment]
@ariabuckles I see you have `***like* this**` as a test case in https://github.com/Khan/simple-markdown/pull/19/files.  Could you add a test case for `***bold** and italics*` to that PR or does it not handle that yet?

**Comment by KatSick** [comment]
Is there any updates ?

**Comment by ariabuckles** [comment]
@KatSick just fixed this with version 0.3.0 / 20b1fefcf2f9aa88f66e1f4a6508832c17ad6f3e .

Sorry about the delay! If you're using this and could let me know how 0.3.0 works for you and if you run into any issues, I'd appreciate any feedback.

@kevinbarabash the `should parse complex combined bold/italics` test case tests this :).
