### ISSUE TITLE
em/strong should handle \-escapes correctly

### ISSUE THREAD

**Issue by ariabuckles** [Khan/simple-markdown#24]
Currently, they end on `*` or `**` without regard to whether it is escaped or not.

**Comment by kevinbarabash** [comment]
@ariabuckles I'm not sure what's meant by `\-escapes`, could you give an example failing case?

**Comment by ariabuckles** [comment]
Two years slow, but this is fixed now, in v0.4.2

Tests for the failing cases:

 * 2eb32df9deb1c64fcf35f9289d7f53d05a0ecd8d : test for the em rule
 * 8f8c8040cb04c19cef989ef45fd48c6f5f6fb256 : test for the strong rule

Fixes for the failing cases:

 * 95d794f5eb4276ed0e16665433ea6e1a794f6116 : fix for the em rule
 * 09e55b4e4930e08a65715ed9493704ed65363384 : fix for the strong rule
