### ISSUE TITLE
way to access context on react rendering

### ISSUE THREAD

**Issue by R3alCl0ud** [Khan/simple-markdown#26]
I want to know if there is a way for me to access the context object when rendering the markdown to react elements

**Comment by xymostech** [comment]
@R3alCl0ud Do you mean like [this context object](https://facebook.github.io/react/docs/context.html)? Where are you trying to access the context? As far as I can tell, accessing it in the react output should work out of the box.

**Comment by R3alCl0ud** [comment]
```js
    roleMention: r({}, parseRules.roleMention, {
      parse: function(e, t, n) {
        var a = (e[0], e[1]),
          i = Client.channels.get(channelId),
          r = i ? i.guild : Client.guilds.get(guildId) || null,
          s = r ? r.roles.get(a) : null;
        return null == s ? {
          type: "text",
          content: "@deleted-role"
        } : {
          type: "mention",
          color: s.color,
          content: [{
            type: "text",
            content: "@" + s.name
          }]
        }
      }
    })
```
I needed to access that context object here

**Comment by xymostech** [comment]
I'm still not sure what context object you are referring to. I'm also not sure what he `roleMention` rule is, that isn't coming from stock simple-markdown. Can you maybe try to explain what you're trying to do a little bit more?

**Comment by ariabuckles** [comment]
I'm guessing by channels/roles and your github it's discord related stuff?

I think you ought to be able to access `this.context` in the `react` function, but you'd probably need to access it through a separate component, which would probably look something like this:

```javascript
class MyElem extends React.Component {
    render() {
        return <div style={{color: this.context.highlightColor}}>
            {this.props.children}
        </div>;
    }
}

// ...

    react: function(node, output, state) {
        return <MyElem>{output(node.content, state)}</MyElem>;
    },
```

**Comment by ariabuckles** [comment]
Closing now unless the above solution isn't working for anyone <3
