### ISSUE TITLE
how to block Source end with one \n

### ISSUE THREAD

**Issue by marlti7** [Khan/simple-markdown#27]
when one \n  output paragraph

**Comment by kevinbarabash** [comment]
@marlti7 can you provide an example with expected and actual output?

**Comment by ariabuckles** [comment]
simple-markdown uses two '\n's to close paragraphs (and all other blocks), as that is generally how paragraphs work in markdown: http://spec.commonmark.org/0.28/#example-183

If this behaviour doesn't match your desired results, you could make a simple-markdown extension to alter it in one of two ways:

1. Add a rule for matching '\n' that outputs a `<br>` inside your paragraph. This is consistent with an option available on some other markdown parsers. To do this, follow [the README's example of customizing the parser](README.md#adding-a-simple-extension) and we want to change the newline rule to output <br>s and the text rule to end before single newlines:

   ```javascript
   var rules = Object.assign({}, SimpleMarkdown.defaultRules, {
       newline: Object.assign({}, SimpleMarkdown.defaultRules.newline, {
           // let's make the newline function return <br>s in react and html
           // (feel free to delete the one you aren't using)
           react: function() { return <br>; },
           html: function() { return "<br>"; },
       }),
       // and we need to modify the text rule too, since by default it matches newlines.
       // we need to let the newline rule *always* match newlines
       text: Object.assign({}, SimpleMarkdown.defaultRules.text, {
           match: SimpleMarkdown.inlineRegex(
               // let's just take the old text regex... and replace the \n\n with \n
               new RegExp(smd.defaultRules.text.match.regex.source.replace('\\n\\n', '\\n'))
           ),
       }),
   });
   ```

2. Change how the block rules break to allow single newlines to end a paragraph. This isn't consistent with any parsers that I know of, but it might be what you want. To do that, we'd need to modify the delimeter part of several block rules' regex, but the most important is that of paragraphs, which I'll demo here. To do this, follow [the README's example of customizing the parser](README.md#adding-a-simple-extension) using a paragraph rule like the following (and any other rules you want to modify):

   ```javascript
   var rules = Object.assign({}, SimpleMarkdown.defaultRules, {
       paragraph: Object.assign({}, SimpleMarkdown.defaultRules.text, {
           match: SimpleMarkdown.blockRegex( // only match elements at a block level
               // this regex seems easier to just replace outright rather than trying to mechanically
               // modify it. it's adapted from the paragraph regex in simple-markdown.js
               // note that the paragraph parser uses `capture[1]` to be the content of the paragraph,
               // so we need to make sure our regex also includes a capture for the content
               /^([^\n]+)\n/
           ),
       }),
   });
   ```

Closing this issue as I think this behaviour is consistent with other parsers, and it should be customizable (above). I'm open to discussing this more/reopening if I'm missing something, though :).
