### ISSUE TITLE
New rule weighting logic sometimes does not choose a rule

### ISSUE THREAD

**Issue by mgreer** [Khan/simple-markdown#33]
Getting an occassional `simple-markdown.js?eb4d:145 Uncaught TypeError: currRule.match is not a function`on the 0.3.0. This does not happen with 0.2.2.

**Comment by ariabuckles** [comment]
Hi! That's not good D:

do you have a markdown string that might reproduce this, or a repo i can check out?

Thanks for reporting this

**Comment by mgreer** [comment]
It looks like it isn't your code, we just had not yet migrated regex: to match: ().

**Comment by ariabuckles** [comment]
Okay thanks! Sorry for the bumpy upgrade path for that

**Comment by mgreer** [comment]
I downgraded to 0.2.2 (fixed for 16 on a fork), but we would like to be on 0.3.0. 

Our issue was in some of our regexes not behaving properly when replacing the straight regex with SimpleMarkdown.inlineRegex. Do you know of any gotchas to look for?

**Comment by ariabuckles** [comment]
SimpleMarkdown.inlineRegex is only applicable for inline elements (i.e. italics, links, etc: when state.inline == true). Maybe they're block rules, in which case you should use SimpleMarkdown.blockRegex.

Alternatively, if it isn't inherently block or inline scoped, or if your rules are potentially not propagating state.inline, SimpleMarkdown.anyScopeRegex ought to be the same behaviour as .regex supported previously
