### ISSUE TITLE
Each child in an array should have a unique "key" prop

### ISSUE THREAD

**Issue by surganov** [Khan/simple-markdown#4]
How to deal with this warning? How can I assign keys to rendered output?

**Comment by ariabuckles** [comment]
Hi! I think the latest commit on master has this fixed! I haven't gone through to make all of the documentation 100% correct with this (I added a new `state` parameter to `output`/`react` extension methods) or npm published, but I intend to do those soon. Are you still seeing this?

**Comment by surganov** [comment]
I installed latest version (0.0.2) via npm and trying to get this work without warnings:
```js
import SimpleMarkdown, {
  defaultBlockParse as mdParse,
  defaultOutput as mdOutput
} from 'simple-markdown';

const syntaxTree = mdParse("Here is a paragraph and an *em tag*.");
console.log(mdOutput(syntaxTree));
```

But I still see this warning: `Each child in an array should have a unique "key" prop. Check the renderComponent call using <undefined>. See http://fb.me/react-warning-keys for more information.`

**Comment by ariabuckles** [comment]
Sorry about that; I haven't updated the npm version in a while. I just updated it to 0.0.3; could you try that out and let me know if it works?

**Comment by surganov** [comment]
It works! There's no warning messages this time. Thanks!

Also, I have an idea of using markdown with react via ES6 template tags:

```jsx
<div>{md`_Hello_ world`}</div>
```

(Consider it as feature request).

And why you don't use react-like AST? It should like this:

```js
[
  'This is an ',
  {
    type: 'em',
    children: [
      {
        type: 'a',
        children: 'link',
        props: {
          href: 'https://www.khanacademy.org'
        }
      }
    ]
  },
  '.'
]
```
