### ISSUE TITLE
Unit testing custom rules

### ISSUE THREAD

**Issue by iqrow** [Khan/simple-markdown#43]
I wonder if there is a recommended route for unit testing custom rules?

In my scenario:
1. I'm modifying some of the default rule `match`, `parse` and `react` functions
1. I'm adding custom rules
1. I want to test all of these on strings

A simplified unit test might look something like
```
  it('Should be able to parse a body with markdown that is simple', function() {
   // custom parser that accepts options and uses simple-markdown at its core
    const actual = parseBody('hello *there* mate', { option: 'foo' })
    const expected = [ 'hello ', md('strong', 'there'), ' mate' ]
    expect(actual).to.deep.equal(expected)
  })
```

The `md` function in this test is what I'm having trouble defining.

1. I tried using `React.createElement('strong')` because I thought that would be what I'm checking against, but there were some differences between `actual` and `expected` (`_store`, `originalProps`, etc.).
1. I tried copying and pasting some of the not exported code from simple-markdown.js into my unit tests to try and recreate how the AST is created in the library (not ideal!). I stopped short of the implementing recursion as that put me on the verge of re-implementing the library in my test suite.
1. I thought maybe all I really care about in this test is whether it's valid simple-markdown AST or perhaps even just valid React AST, but how best to check this?

Do you have any recommendations please? Thank you.

**Comment by ariabuckles** [comment]
Hi!

I'd like to take a shot at directly answering your question, but before that I think some of the ways I test simple markdown internally might be helpful. For that, I use two methods:

1. just do a parse, and test that the AST is what I want
2. render to react, and then use [ReactDOMServer.renderToStaticMarkup](https://reactjs.org/docs/react-dom-server.html#rendertostaticmarkup) to render that react tree to html, clean the html up a bit, then diff the html.

Method 2 might work pretty well for your use case, depending on how custom the react elements you're rendering are. Here's a modified version of the helper function I use for that (in __tests__/simple-markdown.test.js):

```javascript
var reactOutputToHtml = function(output) {
    var rawHtml = ReactDOMServer.renderToStaticMarkup(
        React.createElement('div', null, output)
    );   
    var innerHtml = rawHtml
        .replace(/^<div>/, '')
        .replace(/<\/div>$/, ''); 
    var simplifiedHtml = innerHtml
        .replace(/>\n*/g, '>') 
        .replace(/\n*</g, '<') 
        .replace(/\s+/g, ' ');
    return simplifiedHtml;
};
```

To then test you example, you might use:

```javascript
  it('Should be able to parse a body with markdown that is simple', function() {
   // custom parser that accepts options and uses simple-markdown at its core
    const actual = parseBody('hello *there* mate', { option: 'foo' })
    const expected = 'hello <strong>there</strong> mate'
    expect(reactOutputToHtml(actual)).to.equal(expected)
  })
```

------------------

Alternatively, we could clean up / unify the react nodes we're comparing. Maybe an easy way to do that would be to define a custom matcher for react trees. Then `md` can just be `React.createElement`

If you're using [jest](https://facebook.github.io/jest/docs/en/expect.html#expectextendmatchers), this would look like:

```javascript
var cleanUpReact = function(reactOutput) {
  if (Array.isArray(reactOutput)) {
    if (reactOutput.length === 1) {
      return cleanUpReact(reactOutput[0]);
    }   
    return reactOutput.map(cleanUpReact)
  }
  if (reactOutput == null || typeof reactOutput !== 'object') {
    return reactOutput
  }

  var props = reactOutput.props || {}; 
  var cleanedUpNode = { 
    type: reactOutput.type,
    props: Object.assign({}, props, {
      children: cleanUpReact(props.children),
    }), 
  }

  return cleanedUpNode
}

expect.extend({
  toBeTheSameReactOutput: function(received, argument) {
    received = cleanUpReact(received)
    argument = cleanUpReact(argument)

    var pass = this.equals(received, argument)
    if (pass) {
      return {
        pass: true,
        // called when expect(actual).not.toBeTheSameReactOutput fails:
        message: function() {
          console.log("comparison:", JSON.stringify(received, null, 4), JSON.stringify(argument, null, 4));
          return 'expected react trees to not match'
        },  
      };  
    } else {
      return {
        pass: false,
        // called when expect(actual).toBeTheSameReactOutput fails:
        message: function() {
          console.log("comparison:", JSON.stringify(received, null, 4), JSON.stringify(argument, null, 4));
          return 'expected react trees to match'
        },  
      };  
    }
  },
});

```

Here's a gist of that: https://gist.github.com/ariabuckles/10e940ee229ea5cdc66dad02ad786f21

It looks like maybe you're maybe using chai, and I'd expect them to have a similar mechanism to the above.

------------

Hope one of those options helps! Happy to answer more questions if I can help as you work on this!

**Comment by iqrow** [comment]
Wow, thank you so much for taking the time to put these together. I've gone with the `reactOutputToHtml` and this has unblocked me. I'll add anything else I find helpful as I go through the different cases.

Thanks again!

**Comment by ariabuckles** [comment]
Glad I could help!
