### ISSUE TITLE
strong rule parse issue

### ISSUE THREAD

**Issue by fannairu** [Khan/simple-markdown#45]
When i use simple-markdown to parse the string ` **con**nect`, it will render `<strong>Con</strong><strong>conn</strong>ect`.  The rule which I use is defaultRules.strong; but if i rewrite the react function of the rule as follows:

```javascript
        react: function(node, output, state) {
            return <strong key={state.key}>{output(node.content, state)}</strong>;
        }
```

the error has gone. Which may cause this problem?

**Comment by ariabuckles** [comment]
The default `strong.react` function should be the same as the function you wrote there. Do you have a bigger example you could send me here, or a private gist via email? (aria@joinhorizons.com)

**Comment by ariabuckles** [comment]
Closing as can’t repro for now, but I’m happy to reopen this if there’s some more context I can look into :)
