### ISSUE TITLE
Nested unordered lists parsing/indentation issue

### ISSUE THREAD

**Issue by brianmock** [Khan/simple-markdown#48]
Running into an issue where nested bullets are improperly indented. 

Some background, I use react-rte (https://github.com/sstur/react-rte) to convert a user's rich text input to markdown which I pass to a Markdown component:

```
  0 import React from 'react';
  1 import SimpleMarkdown from 'simple-markdown';
  2
  3 import Content from 'components/Content';
  4
  5 const Markdown = ({ string, className }) => {
  6   if (!string) {
  7     return null;
  8   }
  9
 10   const mdParser = SimpleMarkdown.defaultBlockParse;
 11   const mdOutput = SimpleMarkdown.defaultOutput;
 12
 13   const syntaxTree = mdParser(string);
 14
 15   const content = mdOutput(syntaxTree);
 16
 17   return (
 18     <Content className={className}>
 19       {content}
 20     </Content>
 21   );
 22 };
 23
 24 export default Markdown;
```

An example of the issue -- when I pass the following string (generated by the react-rte lib) to the Markdown component above:
```
- test one
    - thing one
- test two
    - thing two
    - one more thing two
- test three
    - thing three
- test four
```

I end up with the following output, you'll notice the `one more thing two` item is treated as a new ul when it should only be considered another list item of the current ul:
![screen shot 2018-03-05 at 10 46 34 am](https://user-images.githubusercontent.com/12766625/36987698-99001c4c-2062-11e8-907b-613162c7807b.png)
![screen shot 2018-03-05 at 10 45 57 am](https://user-images.githubusercontent.com/12766625/36987699-990fae00-2062-11e8-816a-17acd9915252.png)

Does not happen for ordered lists. 

Here is a [link](https://gist.github.com/brianmock/754e045fb71ce48b9efb0c2b5dce56cd) to the syntaxTree output generated by the mdParser function.
Let me know if there is any additional info you need to help figure out what's going on. Thanks.

**Comment by ariabuckles** [comment]
Confirmed; I think I have an idea what's going on and can probably fix it this week, although it might take a bit of time as I'm pretty busy at work right now.

Thanks!

**Comment by ariabuckles** [comment]
I just pushed version 0.3.3 with a potential fix for this - could you let me know if it works for you (and whether it introduces any other surprises).

\[I expect it to work and not cause problems, of course, but it fixes this in an unusual way and like most things, could potentially interact oddly with custom extensions\]

**Comment by brianmock** [comment]
@ariabuckles Looks great so far! Thanks for the quick turnaround.
