### ISSUE TITLE
Document that users should sanitize HTML

### ISSUE THREAD

**Issue by domoritz** [Khan/simple-markdown#49]
I noticed that HTML is just passed through. This can have unwanted side effects if this plugin is used on a platform where users can provide the content, which is then displayed to other users. 

Here is a demonstration of the problem: https://bl.ocks.org/domoritz/raw/05254ae24b0a69b6e5dbe8a5718ab506/cdf4e1ccf44f193de06f98d78bfa486ee1b53742/.

While it is not necessarily the responsibility of this module to sanitize HTML, I'd say there are two options. First, document in the readme that this module does not sanitize HTML. Second, sanitize all HTML. This would unfortunately mean that one cannot write HTML in markdown anymore but maybe that is not the end of the world.

**Comment by ariabuckles** [comment]
Thanks @domoritz!

I agree 100% this is an issue. In 1.0 I plan to sanitize all HTML (which you can see on 33a9e5d98f45bbd5a17474d9ec40489cff0b6bb0 on branch [prerelease / 1.0.0-alpha.0](https://github.com/Khan/simple-markdown/tree/prerelease).

If you run `npm install simple-markdown@next` you should get version 1.0.0-alpha.0, which includes this fix.

As you mention, this does cause issues with html passthrough, but I don't intend to support that out of the box (building a rule for that is possible, however).

My work has been very busy this semester so I haven't had nearly as much time as I want to spend on this, but I am slowly making progress towards an official 1.0 which includes fixes for this and some other issues. In the meantime though, if you could try `simple-markdown@next` and let me know how that goes, I'd appreciate that.

**Comment by domoritz** [comment]
Thanks for the response. I decided not to include the library by default in https://github.com/vega/vega-tooltip but I'm using simple-markdown as an example in the extension docs. Nonetheless, I have some ideas for uses in some other places. I will report back if I find problems.

**Comment by ariabuckles** [comment]
Sounds good; thanks!
