### ISSUE TITLE
Commas in output

### ISSUE THREAD

**Issue by lwansbrough** [Khan/simple-markdown#5]
I'm seeing commas in the parser output (see here: https://github.com/lwansbrough/react-native-markdown/issues/4) -- perhaps having a look at my implementation code might also help debug this: https://github.com/lwansbrough/react-native-markdown/blob/master/Markdown.js#L40

Here's what it looks like: https://i.imgur.com/zIzROOt.png

**Comment by xymostech** [comment]
What's the React Native code you're rendering to generate that screenshot?

**Comment by lwansbrough** [comment]
```jsx
<Markdown style={{width: 375, overflow: 'hidden'}}>
          Some *really* basic **Markdown**. {'\n\n'}Some *really* basic **Markdown**. Some *really* basic **Markdown**.
          ![alt text](https://github.com/adam-p/markdown-here/raw/master/src/common/images/icon48.png "Logo Title Text 1")
</Markdown>
```

**Comment by spicyj** [comment]
This line's your problem:

https://github.com/lwansbrough/react-native-markdown/blob/master/Markdown.js#L52

`this.props.children` is an array in this case and so you end up with commas casting it like that. You probably want to use React.Children.forEach instead and build up a string yourself.

**Comment by lwansbrough** [comment]
Argh, thanks.
