### ISSUE TITLE
flow issue

### ISSUE THREAD

**Issue by sibelius** [Khan/simple-markdown#50]
![image](https://user-images.githubusercontent.com/2005841/39365035-63907368-4a06-11e8-81a4-3ac62e27cce5.png)

gonna try a fix on this

**Comment by ariabuckles** [comment]
Try installing `simple-markdown@next` (1.0.0-alpha.0) and I think this should be fixed (in 84bd0a1a916e6b6c67f5647c65709d2a64c8cae7 )

Please let me know if you're still getting this issue in 1.0.0-alpha.0

**Comment by ariabuckles** [comment]
Alternatively, try `npm install simple-markdown@0.4.0` which should fix this :)
