### ISSUE TITLE
Unable to escape ordered list

### ISSUE THREAD

**Issue by joepec** [Khan/simple-markdown#53]
I'm trying to get the following string to render as a paragraph:
"1. This is some text"

This gets converted into an ordered list, adding indentation. Is there any way to prevent ordered list rule from picking this up?

![image](https://user-images.githubusercontent.com/6349799/40999666-1a7b1e8c-68d1-11e8-9759-f279727ef29e.png)

**Comment by ariabuckles** [comment]
Hi @joepec, try `"1\. This is some text"`, which should render to:

1\. This is some text

I agree it's weird that `"\1. This is some text"` does not work—by default escapes only work for non-letters or numbers. We might look into revising that if it's causing problems.

**Comment by ariabuckles** [comment]
(Additionally, if you'd prefer to never turn lists into `<ol>`s or `<ul>`s, you can disable the ordered list rule with the following: )

```javascript
var rules = Object.assign({}, SimpleMarkdown.defaultRules, { list: null });

var parse = SimpleMarkdown.parserFor(rules);
var htmlOutput = SimpleMarkdown.outputFor(rules, 'html');
var reactOutput = SimpleMarkdown.outputFor(rules, 'react');

var markdownToHtml = function(source) {
    return htmlOutput(parse(source));
};
var markdownToReact = function(source) {
    return reactOutput(parse(source));
};
```

**Comment by ariabuckles** [comment]
Closing this for now; happy to reopen if that doesn't work for you, or if someone else finds this thread and is running into similar things.

**Comment by joepec** [comment]
@ariabuckles - sorry for the delay. I've tried `1\. This is some text`, but that didn't work. I'm unable to turn off the list rule because I do have some use cases for it.

**Comment by ariabuckles** [comment]
No worries, sorry for closing it early!

Here's what I get when I use `1\. This is some text`:

```
> require('simple-markdown').markdownToHtml('1\\. This is some text\n\n')
'<div class="paragraph">1. This is some text</div>'
```

I forgot to escape the backslash properly in the quoted example before: if the string is user supplied
it should require only one backslash, but if it is in a js file each backslash needs to be itself escaped:

```
> console.log('1\. This is some text\n\n')
1. This is some text


undefined
> console.log('1\\. This is some text\n\n')
1\. This is some text


undefined
```

If you're still seeing the issue, do you have a usage example that I could look at to try to diagnose what could be going wrong?

**Comment by joepec** [comment]
Hi @ariabuckles,

I got it working, thanks!

**Comment by ariabuckles** [comment]
Great @joepec ! Thanks for following up :)
