### ISSUE TITLE
Simplify regular expressions

### ISSUE THREAD

**Issue by faergeek** [Khan/simple-markdown#56]
Hello. I'd like to simplify codebase a bit. I really like to do that.

What about simplifying regular expression using literals and getting strings from [source prop](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/source)? It helps by greatly decreasing the number of backslashes and increasing readability.

Example:

```javascript
/\r\n?/g.source === '\\r\\n?' // true
```

Note that I'm not 100% sure about browser compatibility yet, there are many question marks on mdn compatibility table. But I used that on production websites and there was no issue in browsers I needed to support. If idea sounds good I will test on many different browsers. BTW is there list of supported browsers somewhere?

**Comment by ariabuckles** [comment]
Yeah, it's fine if you use .source while changing specific regular expressions / rules (but please don't replace all of the regular expressions with that).
