### ISSUE TITLE
Prettier

### ISSUE THREAD

**Issue by faergeek** [Khan/simple-markdown#57]
Continuing part of discussion from https://github.com/Khan/simple-markdown/pull/55

I understand that prettier more likely will break flow annotations in comments, so it may require using syntax without comments and https://github.com/flowtype/flow-remove-types or something like that.

On the plus side it simplifies contributing (I really don't like to format my code manually anymore) and also tooling support is better, e.g. taking into account just vscode: https://github.com/flowtype/flow-for-vscode/issues/128, https://github.com/flowtype/flow-for-vscode/issues/96, https://github.com/flowtype/flow-for-vscode/issues/46

So I think it's worth it. What do you think?

**Comment by ariabuckles** [comment]
I'm not interested in using prettier until they add support for flow comments. I know reformatting by hand isn't fun, but it works and it's doable.
