### ISSUE TITLE
Error on custom extension

### ISSUE THREAD

**Issue by Radivarig** [Khan/simple-markdown#6]
I've set the code for extension with underlineRule from README.md. At first everything seem to work, but I figured that it is so because the rule is already in the default ruleset. So, when I change regex to anything else and I parse the string that will match, I get the following error:
```js
 Uncaught TypeError: rules[ast.type][property] is not a function  //simple-markdown.js: 1293
```

**Comment by Radivarig** [comment]
I was missing `react: function (...` or `html: function (...`
I added one as found in other default rules and I get error:
```js
could not find rule to match content: source_arg  //simple-markdown.js: 137
//where source_atg is a string argument of rule.match
```

**Comment by ariabuckles** [comment]
Hi! Apologies on the underline rule; I've been meaning to remove underlines from the actual grammar and moving those over to extensions, which would make that example make more sense.

I don't think I fully understand what you mean--could you upload your code somewhere so I can check it out?

**Comment by Radivarig** [comment]
Hi, this is the copy pasted example, with change of the rule name and regex from wrapping in `__` to `xx`. You will see the first error, and if you add the method above you will get the second error.

```js
var _ = require('underscore')
var SimpleMarkdown = require('simple-markdown')

var xxRule = {
  order: SimpleMarkdown.defaultRules.em.order - 0.5,
  match: function(source) {
    return /^xx([\s\S]+?)xx(?!x)/.exec(source)
  },
  parse: function(capture, parse, state) {
    return {
        content: parse(capture[1], state)
    }
  },
  output: function(node, output) {
    return React.DOM.u(null, output(node.content))
  }
}

var rules = _.extend({}, SimpleMarkdown.defaultRules, {
  xx: xxRule
})

var rawBuiltParser = SimpleMarkdown.parserFor(rules)
var parse = function(source) {
  var blockSource = source + "\n\n"
  return rawBuiltParser(blockSource, {inline: false})
}
var output = SimpleMarkdown.outputFor(SimpleMarkdown.ruleOutput(rules))

var ReactFromString = React.createClass({
, render: function() {
    var source = this.props.inputText
    var syntaxTree = parse(source) //+'\n\n'
    return React.DOM.div(null, output(syntaxTree))
  }
})
```

**Comment by Radivarig** [comment]
This weekend I'll dedicate some time to the issue, so it would be cool if you'd take a look by then and write your thoughts on it to direct me on where the problem might be, I'll be glad to make a pull request (documentation and potential fixes) once we make it work. Thanks

**Comment by ariabuckles** [comment]
Sorry, I just started a new job (and no longer work at KA). I'll try to see if I can figure out what's going on.

**Comment by ariabuckles** [comment]
When I run the following code, I seem to get the expected output:

```
var _ = require('underscore')
var React = require('React');
var SimpleMarkdown = require('simple-markdown')

var xxRule = {
  order: SimpleMarkdown.defaultRules.em.order - 0.5,
  match: function(source) {
    return /^xx([\s\S]+?)xx(?!x)/.exec(source)
  },
  parse: function(capture, parse, state) {
    return {
        content: parse(capture[1], state)
    }
  },
  react: function(node, output) {
    return React.DOM.u(null, output(node.content))
  }
}

var rules = _.extend({}, SimpleMarkdown.defaultRules, {
  xx: xxRule
})

var rawBuiltParser = SimpleMarkdown.parserFor(rules)

var parse = function(source) {
  var blockSource = source + "\n\n"
  return rawBuiltParser(blockSource, {inline: false})
}

var output = SimpleMarkdown.outputFor(SimpleMarkdown.ruleOutput(rules))

var inputText = 'xxsome textxx'
var source = inputText;
var syntaxTree = parse(source);

console.log(output(syntaxTree));
```

The changes I've made from yours are:

 * added require('React') (which you probably have in the global scope?)
 * changed the `output:` function to `react:` (like you mention)
 * changed the react rendering to console.logs so i could run it easily in node

Am I missing something else? does the above code work for you?

I'll go through the documentation and make that actually consistent with the latest version (`react:` mostly, but I should move `u` out of the default ruleset sometime).

**Comment by ariabuckles** [comment]
Hopefully some slightly better documentation here:

https://github.com/Khan/simple-markdown/commit/215c706fa295ebcdb6e4cee7ca5c7747d1050e7b

If you have questions on those changes I'd be happy to answer them when I have time, or if you have better ways of explaining anything, I'd be happy to accept a PR <3.

**Comment by Radivarig** [comment]
It works, it's the same code but I use the latest of react and npm now, might have been improper dependencies nesting. Still thanks :)

**Comment by ariabuckles** [comment]
Yay!
