### ISSUE TITLE
Escaped pipe chars in table creates new cells

### ISSUE THREAD

**Issue by robaxelsen** [Khan/simple-markdown#68]
Hi :wave: Thanks for a great library :tada: Loving it :heart: 

I've been running into an issue within storybook, that uses markdown-to-jsx, which again is using simple-markdown to parse markdown.

The issue I am experiencing can be found [described in detail here.](https://github.com/storybookjs/storybook/issues/6869)

I also made a crude test repo to check that the same base output also is found in the simple-markdown `syntaxTree`, which turned out to be the case: https://github.com/robaxelsen/markdown-to-jsx-table-pipe-test

Any chance someone could help fix this, or help illuminate the logic behind ignoring the escaped pipe characters, please? Any help greatly appreciated :pray:

**Comment by ariabuckles** [comment]
Hi @robaxelsen ! I'm really glad it's been useful to you!

This definitely looks like a bug; several of the other parsing rules use a particular pattern to allow escaping characters, but tables may not. I'll see what I can do.

**Comment by ariabuckles** [comment]
I think I've fixed this in `simple-markdown@0.5.0`. The 

One important note: The fix I implemented makes:

`` `"left" \| "right"` `` parse as `<code>"left" \| "right"</code>` not `<code>"left" | "right"</code>`. To get the single `|`, you should not escape it, since it's inside a code element (which generally doesn't support escaping, but should only end at the corresponding `` ` ``.)

So for your example,

```
| Attribute    | Type                  |
| ------------ | --------------------- |
| `position`   | `"left" | "right"`    |
```

should get you what you want.

I'll see if it's easy to port this to markdown-to-jsx, I didn't actually know of that fork

**Comment by ariabuckles** [comment]
I sent a PR to markdown-to-jsx too: https://github.com/probablyup/markdown-to-jsx/pull/261

I briefly tested this in your test repo, but not extensively. Please feel free to re-open if this doesn't work for you!

**Comment by robaxelsen** [comment]
@ariabuckles wow, that's amazing! Thanks for the thorough reply, and for fixing it PLUS submitting a PR to `markdown-to-jsx`. Grateful for all the help :heart:

**Comment by ariabuckles** [comment]
You're welcome; glad I could help, and thanks for reporting it!

(also I apparently caught a rogue `.git` directory in `0.5.0` , if you're using that anywhere permanently you might want to `rm -rf node_modules/simple-markdown/.git && npm i simple-markdown@latest`)

**Comment by robaxelsen** [comment]
> You're welcome; glad I could help, and thanks for reporting it!

You're welcome :smile: 

> (also I apparently caught a rogue `.git` directory in `0.5.0` , if you're using that anywhere permanently you might want to `rm -rf node_modules/simple-markdown/.git && npm i simple-markdown@latest`)

Got it, thanks!
