### ISSUE TITLE
Rogue return character in the reactFor array?

### ISSUE THREAD

**Issue by ardeaf** [Khan/simple-markdown#79]
I have no idea why this custom rule is showing a return character in the reactOutput array (see below for the output)

I'm trying to make a rule that matches `>!spoilers!<`, which in this case should take the text `spoilers` and render that text in react.

![image](https://user-images.githubusercontent.com/20672831/68255090-65efb700-ffd0-11e9-880a-50e4c4b94d5b.png)

The Markdown component:
```
const Markdown: React.FC<MarkdownProps> = ({ theme, content }) => {
  const rules = generateRules(theme);
  const rawBuiltParser = SimpleMarkdown.parserFor(rules);
  const parse: Parser = (source) => {
    const blockSource = source + '\n\n';
    return rawBuiltParser(blockSource, { inline: false });
  };
  const reactOutput = SimpleMarkdown.reactFor(SimpleMarkdown.ruleOutput(rules, 'react'));
  console.log(reactOutput(parse(content)));
  return <View>
    {reactOutput(parse(content))}
  </View>;
```

The spoiler rule, it gets merged into the default rules with lodash `_.merge()`
```
    spoilers: {
      order: SimpleMarkdown.defaultRules.blockQuote.order - 0.5,
      match: source => /^>!([\s\S]+?)!</.exec(source),
      react: (node, output, state) => createElement(Text, {
        style: { textDecorationLine: 'line-through' },
        key: state.key
      }, output(node.content, state)),
      parse: (capture, parse, state) => ({
        content: parse(capture[1], state)
      })
    },
```

**Comment by ardeaf** [comment]
Well I ended up fixing it by changing the regex to make sure the closing tag is the end of the regex: `match: anyScopeRegex(/^>!([\s\S]+?)!<$/),`

Though, I'm not 100% sure if that'll break something else.

**Comment by ardeaf** [comment]
With some further tweaks this seems to be the proper way to do it. I set order to 0 so it has the highest priority:

```
    spoilers: {
      order: 0,
      match: inlineRegex(/^>!(.+?)!</),
      react: (node, output, state) => createElement(Text, {
        style: { textDecorationLine: 'line-through' },
        key: state.key
      }, output(node.content, state)),
      parse: (capture, parse, state) => ({
        content: parse(capture[1], state)
      })
    },
```

**Comment by ariabuckles** [comment]
Hi!

I think you've found a great solution to this, but to to into some detail about why I think you were seeing issues earlier:

This looks to me like the earlier rules were likely matching at a block scope, before a paragraph had been created. This left a rogue newline at the end of the input, which should be matched by the newline rule, which is:

```
    newline: {
        match: blockRegex(/^(?:\n *)*\n/),
        parse: ignoreCapture,
        react: function(node, output, state) { return "\n"; },
        html: function(node, output, state) { return "\n"; }
    },
```

So a few ways you can fix it (one of which you found!):

1. Use the `inlineRegex` helper like you did in the last example. I think the first regex should work fine wrapped in `inlineRegex` too, if you want to allow newlines within the spoiler tag.
2. Move the rule's order after paragraph with something like `order: SimpleMarkdown.defaultRules.paragraph.order + 0.5`
3. Modify the `newline` rule to not output a `\n` (`newline: Object.assign({}, SimpleMarkdown.defaultRules.newline, { react: () => null })`)

I think your existing solution of using `inlineRegex` is probably the best of those options, but if your needs change or if I didn't think of something, it's possible adjusting the order like in option 2 might be useful.

**Comment by ardeaf** [comment]
Thanks.
