### ISSUE TITLE
could not find rule to match content:

### ISSUE THREAD

**Issue by Radivarig** [Khan/simple-markdown#9]
In my case the error `could not find rule to match content:` was raised because the rules do not match a block source without newlines `\n\n`, and `inline: false` is default option making the rule to expect a block.
First match was a block but its nested parse substring was not, so the `text` rule was skipping it. 

I solved it by setting `state.inline = true` in return of the `parse` function.
```
parse: function(capture, parse, state) {
    state.inline = true
    return { content: parse(capture[1], state)}
}
```
Might be useful for documentation

**Comment by ariabuckles** [comment]
Hi Reslav!

Correct, if you're parsing inline content from a block element, you'll have to do what you said. We should document this.

There are also helper methods `SimpleMarkdown.parseInline` and `SimpleMarkdown.parseBlock` that can do this wrapping for you:

```javascript
parse: function(capture, parse, state) {
  // Note the first parameter has to be our recursive `parse` function:
  return { content: SimpleMarkdown.parseInline(parse, capture[1], state)}
}
```

The code for `parseInline` looks like:
```javascript
var parseInline = function(parse, content, state) {
    var isCurrentlyInline = state.inline || false;
    state.inline = true;
    var result = parse(content, state);
    state.inline = isCurrentlyInline;
    return result;
};
```

(It uses mutation as opposed to the cleaner `Object.assign` to avoid the extra two allocations).

I'm not super happy with this whole inline/block system yet, though. I'm not sure it will stay exactly like this over time.
