### ISSUE TITLE
Security Issue: Request for contact

### ISSUE THREAD

**Issue by pwntester** [Khan/simple-markdown#92]
Hello,

The [GitHub Security Lab team](https://securitylab.github.com/) has found a potential vulnerability in your project. Please create a [Security Advisory](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/creating-a-security-advisory) and invite me in to further disclose and discuss the vulnerability details and potential fix. Alternatively, please add a [Security Policy](https://docs.github.com/en/free-pro-team@latest/github/managing-security-vulnerabilities/adding-a-security-policy-to-your-repository) containing a security email address to send the details to.

Kind regards,
A

**Comment by ariabuckles** [comment]
Hi @pwntester !

Thank you so much for contacting me! Sorry about the late response; I've been struggling a lot during the pandemic.

I'd love to hear the details about this at aria+security@toole1.com , and added a [security policy](SECURITY.md).

(I don't have admin rights to make security advisories on the repo as I no longer work at Khan Academy, but I continue to be the maintainer for this project)

**Comment by pwntester** [comment]
Thanks, just sent you the report

**Comment by ariabuckles** [comment]
Fixed in #95 / version `0.7.3`

Thanks again @pwntester !
