### ISSUE TITLE
Cannot change image syntax

### ISSUE THREAD

**Issue by Diamond-Frost** [Khan/simple-markdown#98]
I'm writing a Documentation server and using simple-markdown for markdown handling, and adding syntax nodes (i.e. checkboxes, etc), and upon attempting to add syntax to easily change image sizes, it failed me. I am unable to change the syntax, as once activating my new syntax, the image will be parsed like a link with a preceding "!" (I tested the regex multiple times over and over, all tests have passed, and it should work).

I also tried changing the syntax entirely, and it still would not parse it. I do not know what to do anymore.

This is the definition of my slightly changed syntax.
```js
let image = {
    order: SimpleMarkdown.defaultRules.image.order - 0.5,
    match: inlineRegex(/^!\[([^=]+)(?:=(\d+)x(\d+)?)?\]\(\s*<?((?:\([^)]*\)|[^\s\\]|\\.)*?)>?(?:\s+["']([^\s"]+)['"]\s*)?\)/),
    parse: (capture, parse, state) => {
        return {
            alt: capture[1],
            height: parseInt(capture[2]),
            width: parseInt(capture[3]),
            target: unescapeUrl(capture[4]),
            title: capture[5],
        };
    },
    react: (node, output, state) => 
        <img
            key={state.key} 
            src={sanitizeUrl(node.target)} 
            alt={node.alt} 
            title={node.title}
            height={node.height}
            width={node.width}
        />
};
```

**Comment by ariabuckles** [comment]
Hi @Diamond-Frost !

Image sizes sound really useful for authors; I love it.

I'm trying to reproduce the issue, but your rule is working for me with the following test code:

```javascript
const SimpleMarkdown = require("simple-markdown");

let image = {
    order: SimpleMarkdown.defaultRules.image.order - 0.5,
    match: SimpleMarkdown.inlineRegex(/^!\[([^=]+)(?:=(\d+)x(\d+)?)?\]\(\s*<?((?:\([^)]*\)|[^\s\\]|\\.)*?)>?(?:\s+["']([^\s"]+)['"]\s*)?\)/),
    parse: (capture, parse, state) => {
        return {
            alt: capture[1],
            height: parseInt(capture[2]),
            width: parseInt(capture[3]),
            target: SimpleMarkdown.unescapeUrl(capture[4]),
            title: capture[5],
        };
    },
};

const rules = {
  ...SimpleMarkdown.defaultRules,
  image
};

const rawBuiltParser = SimpleMarkdown.parserFor(rules);
const parse = function(source) {
    var blockSource = source + "\n\n";
    return rawBuiltParser(blockSource, {inline: false});
};

console.log(JSON.stringify(
  parse('![alt=640x480](http://example.com/test.png "title")'),
  null,
  4
));
```

that prints the following for me:

```
[
    {
        "content": [
            {
                "alt": "alt",
                "height": 640,
                "width": 480,
                "target": "http://example.com/test.png",
                "title": "title",
                "type": "image"
            }
        ],
        "type": "paragraph"
    }
]
```

Is there any chance you didn't add your image rule to a rules object, and construct a parser from that?

If it's possible to send me the whole file or test case, I'd be happy to look into it further!

**Comment by Diamond-Frost** [comment]
Hello, I've had the project on hold for a bit now due to work, but I've just tried your rule, and it also was overruled by the link syntax (I'm using Next.js and have a local link syntax, which works fine, the `SimpleMarkdown.defaultRules.link` syntax is the one overruling the image. I've tried with the local link syntax removed from the rules object, which still didn't change anything. I'll get back on this very shortly, to upload it to GitHub and give a test file.

**Comment by Diamond-Frost** [comment]
I've uploaded it to [GitHub](https://github.com/Diamond-Frost/NextDocument) now, in which I've also created a test file, which oddly enough works, however, in a different file, which is then supposed to be used in the finished version, it cannot import a file (it can import the test file however)

**Comment by Diamond-Frost** [comment]
Nevermind, the issue was my usage. I've had a space in the title, which the image syntax you provided did not allow, however, upon discovering this, I've changed it and the file works now, thank you for your patience and implementation.
